let handler = async (m, { conn }) => {
  conn.reply(m.chat, `“${genBucin()}”`, m);
};
handler.help = ["bucin"];
handler.tags = ["quotes"];
handler.command = /^(bucin)$/i;

module.exports = handler;

function pickRandom(list) {
  return list[Math.floor(Math.random() * list.length)];
}

function genBucin() {
  return pickRandom([
    "I choose to be alone, not because I'm waiting for someone perfect, but because I need someone who won't give up.",
    "A single soul was created alongside its soulmate, just not yet found.",
    "Being single is sometimes God's way of saying, 'Take a break from the wrong love.'",
    "Single life is for those building themselves for a love that's truly worth it.",
    "I'm not looking for someone perfect, I'm looking for someone whose flaws I can embrace perfectly.",
    "Someone else's lover might be our soulmate in waiting.",
    "Single now doesn't mean forever. One day, all this loneliness will turn into the sweetest togetherness.",
    "Romeo died for Juliet, Jack saved Rose. Moral: if you want to survive, stay single 😂.",
    "I'm searching for someone whose heart speaks louder than their looks.",
    "Soulmates aren't like flip-flops that get switched easily. Stay in the right fight.",
    "If you were a guitar string, I'd never want to be a guitarist. I wouldn't dare to snap you.",
    "If loving you is an illusion, let me live in that dream forever.",
    "My only task is to love you, not fight fate.",
    "An hour with you feels like a second. A day without you feels like a year.",
    "Even if distance keeps us apart, my love for you never fades.",
    "I want to be your only one, not just one of your options.",
    "I can't promise to be perfect, but I promise to always stand by you.",
    "If I were a politician, I'd fail. How could I think of citizens when you're always in my mind?",
    "Look at my garden, full of flowers. Look at your eyes, making my heart bloom.",
    "Promise me you'll stay — now, tomorrow, and forever.",
    "Distance doesn't cause longing. It's the dreams we can't fulfill yet.",
    "You’ll never truly be far from me — you live in my heart.",
    "Even if distance separates us, our hearts remain close.",
    "Missing you without meeting you is like composing a song that can never be sung.",
    "There are times when distance stands between us — but not in my heart.",
    "If my heart can't hold back this longing, all I can do is pray for you.",
    "I may only hold onto my longing for now, but one day, I’ll embrace you for real.",
    "My heart is a storm of missing you, needing your loving arms.",
    "On cold nights, I lose count — how many times have I missed you?",
    "Missing you feels like sudden rain: heavy, endless, and even when it stops, it lingers.",
    "Since I met you, I just want to keep learning — learning how to be the best for you.",
    "You know the difference between a pencil and your face? A pencil's line can be erased, but your face is stuck in my mind forever.",
    "My biggest exam isn't academic. It's surviving after you left.",
    "Seeing your smile at school every day is my happiness.",
    "Going to school, I bring books and pens. Going to your house? I just bring my heart and love.",
    "I'm not sad because Monday's coming. I'm sad because I might not see you.",
    "My love for you is perfectly balanced with yours. We meet at the equilibrium of love.",
    "I'd run around the world if you're the finish line.",
    "My homework is missing you — stronger than Math, deeper than Physics, and heavier than Biology.",
    "My love for you is like metabolism — it won't stop until I die.",
    "If your spirit is like a spirit from Jelankung, I'd happily pick you up and bring you home.",
    "I'd eat anything, as long as it's with you — even heartache.",
    "Love is like a death sentence. If it doesn't shoot you, it'll hang you.",
    "Loving you is like an addiction — once tried, forever hooked.",
    "I love snacking — especially snacking on the thought of owning your heart completely.",
    "This world only belongs to you and me. The rest? They're just renting space 😂.",
    "Every day with you feels like Tuesday — a little heaven on Earth.",
    "Let's be criminals together. I'll steal your heart, and you steal mine.",
    "You're like my morning coffee — bitter but addicting.",
    "I envy your lipstick. It kisses you every day.",
    "Just hearing your name makes me smile like an idiot.",
    "I know I'm not the only girl who likes you — but my love is unique.",
    "Since I gave up hoping for you, I've lost my fire for everything.",
    "Loving you was the sweetest heartbreak I ever chose.",
    "It's hard to feel alive without you beside me.",
    "Even distance can't stop my heart from aching for your embrace.",
    "If only you knew, I still love you after all this time.",
    "I'm jealous of kites. Even if their strings break, someone still chases after them.",
    "I didn't know what love was until I met you. But then I learned heartbreak too.",
    "Chasing is exhausting, but waiting for you to notice me is even harder.",
    "Don't stop loving just because you’ve been hurt. No rainbow without rain.",
    "I have a million reasons to forget you. Yet, none strong enough to make me stop loving you.",
    "Sometimes people look foolish simply because they love someone too much.",
    "You are my sweetest heartbreak — one I’ll never regret.",
    "It's not that you're unworthy of waiting for. It's just... you keep giving false hope.",
    "Part of me feels broken, knowing how close you are yet so unreachable.",
    "The best part of loving someone is secretly praying for them.",
    "I wish I could erase my feelings for you as easily as you forgot me.",
    "For love, we lie to ourselves — pretending to be strong, but falling so easily.",
    "Consider me your home. You can come back anytime you want, or leave if you're tired.",
    "Am I allowed to be upset? Or should I stay silent, pretending not to care?",
    "My longing for you stands tall like a leafless tree — alone but still standing.",
    "Maybe we're just two strangers now, bonded only by shared memories.",
    "Teach me how to hate you, even for just a few minutes. It'll make forgetting you easier.",
    "I gave you all my love, but you gave yours to someone else.",
    "Maybe loving you broke me. But leaving you didn't fix me either.",
    "You were always my first choice. I was never yours.",
    "If we can only meet in dreams, I want to sleep forever.",
    "Seeing you happy is enough for me, even if I'm not the reason anymore.",
    "I envy objects. They're needed, even without feelings. Unlike me — left behind despite caring.",
    "How can I move on when my heart is rooted in you?",
    "Memories of you are like my home. No matter where my mind wanders, it always returns to you.",
    "Why are tissues important? Because love never dries up. - Sujiwo Tejo",
    "If loving you is wrong, then let me be wrong forever.",
    "Ever since I met you, I've been studying hard — to be better for you.",
    "Some people act like fools, just to see you smile.",
    "I'm not the best person, but I'll strive to be the best for you.",
    "We don't die, but the scars stop us from walking like we used to.",
    "Your presence is like a morning coffee I can't live without — fueling my spirit daily.",
    "I'd love to give you the world, but since I can't, I'll give you the most important thing: my whole world.",
    "Better to be funny and sweet than romantic but tragic.",
    "Sometimes, to avoid disappointment, we have to know when to hope and when to let go.",
    "I'm Javanese. I don't understand 'I love you,' but I know 'Aku tresno awakmu' (I love you deeply).",
    "I don't need your beauty or your wealth — your loyalty is enough to make me happy.",
    "My love for you is like a camera — focused on you, while everything else blurs.",
    "Every day I dream about you, even if I can't have you.",
    "30 days without you feels like a whole year.",
    "Without you, I'm like rice without side dishes — empty and bland.",
    "If only I could turn back time, I'd find you earlier — to spend more of my life with you.",
    "I didn't know what love was until you entered my life.",
    "Even if I marry again, my heart still belongs to you.",
    "My patience has limits, but my love for you is infinite.",
    "My love won't fade, even if cleaned with Bayclin (strong bleach) 😂.",
    "Our memories will always stay, no matter how much time passes.",
    "I can't live alone. I need someone — especially you.",
    "My love for you is like a debt collector — chasing endlessly.",
    "Even though patience has limits, my love for you never runs out.",
    "I wish I could gather every love word in this world and offer it all to you.",
    "My love is like Krispatih’s song: timeless, never fading.",
    "I'm not perfect for you, but I'm the one who constantly remembers you.",
    "Let it just be the internet connection that gets lost, not you.",
    "You often hurt me, but knowing you're still here makes me happy again.",
    "My enemies are those who want to steal you from me.",
    "Many people are available — but only you occupy my heart.",
    "My sleep schedule is destroyed — thanks to missing you.",
    "Let it be China that's far. Not our love.",
    "Your happiness is my priority — even if I'm not.",
    "I only have one wish: to be loved by you.",
    "Without you, I'm like an ambulance with no siren.",
    "Let Antarctica be distant. Not the distance between us.",
  ]);
}
